# Site settings
title: 6-am clothing
email: info@6-amclothing.com
description: > # this means to ignore newlines until "baseurl:"
  For the early riser.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 6-am
# github_username:  

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"
